// Worked examples: real near-misses from the other integrations built in this repository. Each one cites the log it came from,
// and loads a request into the checker that reproduces the mistake. Quotes are verbatim from the projects' BUILD-LOG files.
export const EXAMPLES = [
  {
    id: 'cancelled-op', project: 'Cancelled-Op', folder: 'projects/cancelled-op', surface: 'Payouts',
    does: 'Repays patients for out-of-pocket costs after an NHS operation is cancelled and no new date comes within 28 days.',
    missed: 'It assumed PayPal-Request-Id would stop a payout being sent twice.',
    quote: 'PayPal-Request-Id replay does NOT dedupe payouts in this sandbox: same Request-Id + new sender_batch_id created a 2nd batch. The deterministic sender_batch_id is the real guard.',
    log: 'projects/cancelled-op/BUILD-LOG.md', traps: ['payout-request-id-not-enough', 'payout-dup-batch-id'],
    text: 'POST /v1/payments/payouts\nContent-Type: application/json\nPayPal-Request-Id: cop-case-{{uniq}}\n\n{\n  "sender_batch_header": { "sender_batch_id": "cop-case-{{uniq}}", "email_subject": "Your costs have been repaid" },\n  "items": [{ "recipient_type": "EMAIL", "amount": { "value": "12.34", "currency": "GBP" }, "receiver": "sb-patient@personal.example.com", "note": "Out-of-pocket costs", "sender_item_id": "case-{{uniq}}" }]\n}',
  },
  {
    id: 'dispute-defence', project: 'Dispute Defence', folder: 'projects/dispute-defence', surface: 'Disputes',
    does: 'Fights PayPal disputes on their merits and files evidence before the seller response deadline.',
    missed: 'It tested with a dispute id it had made up. The id belonged to another merchant.',
    quote: 'the id PP-D-48201 I had invented happens to be a real sandbox dispute of someone else (403). Fixtures renamed from PP-D-48xxx to FX-D-48xxx so they can never collide with a real id.',
    log: 'projects/dispute-defence/BUILD-LOG.md', traps: ['disputes-invented-id'],
    text: 'GET /v1/customer/disputes/PP-D-48201',
  },
  {
    id: 'escrow', project: 'Milestone Escrow', folder: 'projects/escrow', surface: 'Payouts',
    does: 'Holds disaster-rebuild money against construction milestones and pays the whole contractor chain in one batch.',
    missed: 'It read the batch status. The batch said SUCCESS while every item was UNCLAIMED, and the sandbox enforced none of the three documented per-item caps.',
    quote: 'Batch status reached SUCCESS while every item was UNCLAIMED. Batch SUCCESS != money delivered. The product reads item status, never batch status.',
    log: 'projects/escrow/BUILD-LOG.md', traps: ['payout-201-is-acceptance', 'payout-per-item-cap', 'payout-unregistered'],
    text: 'POST /v1/payments/payouts\nContent-Type: application/json\n\n{\n  "sender_batch_header": { "sender_batch_id": "esc-{{uniq}}", "email_subject": "Milestone released" },\n  "items": [{ "recipient_type": "EMAIL", "amount": { "value": "20000.01", "currency": "USD" }, "receiver": "callcheck-gc-{{uniq}}@example.com", "note": "Milestone 1", "sender_item_id": "m1-{{uniq}}" }]\n}',
  },
  {
    id: 'holdfast', project: 'Holdfast', folder: 'projects/guarantee', surface: 'Orders and Vault',
    does: 'Authorizes an emergency-surgery guarantee against a sponsor\'s vaulted PayPal wallet.',
    missed: 'It planned to vault a card. The account is outside the countries where PayPal allows that.',
    quote: 'Raw card vaulting: NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE. Raw card orders: PAYEE_NOT_ENABLED_FOR_CARD_PROCESSING. Sandbox app has no card processing. PayPal-wallet vaulting WORKS.',
    log: 'projects/guarantee/BUILD-LOG.md', traps: ['orders-card-source', 'orders-vault-id-stored-credential', 'vault-wallet-urls'],
    text: 'POST /v3/vault/setup-tokens\nContent-Type: application/json\nPayPal-Request-Id: hf-vault-{{uniq}}\n\n{\n  "payment_source": { "card": { "name": "Sponsor", "number": "4111111111111111", "expiry": "2030-12", "security_code": "123" } }\n}',
  },
  {
    id: 'pre-price', project: 'Pre-Price', folder: 'projects/pre-price', surface: 'Invoicing and Subscriptions',
    does: 'Reads a hospital\'s price file, issues a PayPal invoice as the quote, and turns it into an instalment plan.',
    missed: 'The invoice number PayPal generated for it was too long for PayPal\'s own create call.',
    quote: 'PayPal generate-next-invoice-number gives >25 char value its own create rejects. Fully-paid external invoices show MARKED_AS_PAID not PAID.',
    log: 'projects/pre-price/BUILD-LOG.md', traps: ['invoice-number-length', 'subscription-approval'],
    text: 'POST /v2/invoicing/invoices\nContent-Type: application/json\n\n{\n  "detail": { "invoice_number": "QUOTE-HOSPITAL-47562-2026-10-0001", "currency_code": "USD" },\n  "invoicer": { "business_name": "Pre-Price" },\n  "primary_recipients": [{ "billing_info": { "email_address": "sb-patient@personal.example.com" } }],\n  "items": [{ "name": "Knee arthroscopy", "quantity": "1", "unit_amount": { "currency_code": "USD", "value": "4210.00" } }]\n}',
  },
  {
    id: 'tailrace', project: 'Tailrace', folder: 'projects/render', surface: 'Payouts and Invoicing',
    does: 'Chases overdue invoices and pays the corrected address once a customer replies.',
    missed: 'A test payout went to the sending account. PayPal accepted it, then refused it.',
    quote: 'the sending business account itself -> batch DENIED, item FAILED / SELF_PAY_NOT_ALLOWED. Repeating a sender_batch_id returns 400 USER_BUSINESS_ERROR with a link to the existing batch, even with the same PayPal-Request-Id.',
    log: 'projects/render/BUILD-LOG.md', traps: ['payout-self-pay', 'payout-dup-batch-id'],
    text: 'POST /v1/payments/payouts\nContent-Type: application/json\n\n{\n  "sender_batch_header": { "sender_batch_id": "tr-{{uniq}}", "email_subject": "Corrected address" },\n  "items": [{ "recipient_type": "EMAIL", "amount": { "value": "1.00", "currency": "USD" }, "receiver": "sb-mixsn53098231@business.example.com", "sender_item_id": "tr-{{uniq}}" }]\n}',
  },
  {
    id: 'cutoff', project: 'Cutoff', folder: 'projects/bryntum', surface: 'Disputes and Invoicing',
    does: 'A triage board that turns a dispute into a recorded refund invoice.',
    missed: 'It sent PayPal-Request-Id on invoice create and expected a retry to be safe.',
    quote: 'Invoicing v2 ignores PayPal-Request-Id on create (checked: three calls, three invoices), so the idempotency key is a deterministic invoice number. A repeat comes back as DUPLICATE_INVOICE_NUMBER and counts as "already requested".',
    log: 'projects/bryntum/backend/src/paypal.js', traps: ['invoice-request-id-ignored', 'invoice-number-dup'],
    text: 'POST /v2/invoicing/invoices\nContent-Type: application/json\nPayPal-Request-Id: cut-refund-{{uniq}}\n\n{\n  "detail": { "invoice_number": "CUT-{{uniq}}", "currency_code": "USD", "reference": "PP-D-FX-1" },\n  "invoicer": { "business_name": "Cutoff" },\n  "primary_recipients": [{ "billing_info": { "email_address": "buyer@example.com" } }],\n  "items": [{ "name": "Disputed order", "quantity": "1", "unit_amount": { "currency_code": "USD", "value": "25.00" } }]\n}',
  },
  {
    id: 'tripwire', project: 'Tripwire', folder: 'projects/aggrid', surface: 'Payouts, Orders and Invoicing',
    does: 'Watches a stream of PayPal activity and flags anomalies.',
    missed: 'A PAYPAL_ID payout that looked valid. Its own log and Cancelled-Op\'s disagree on what the batch status shows.',
    quote: 'PAYPAL_ID bogus id ends FAILED / RECEIVER_ACCOUNT_INVALID while the BATCH reads SUCCESS. Item status is the truth. (Cancelled-Op recorded the same payout as batch DENIED; the run in this repository says DENIED.)',
    log: 'projects/aggrid/BUILD-LOG.md', traps: ['payout-paypal-id', 'payout-201-is-acceptance'],
    text: 'POST /v1/payments/payouts\nContent-Type: application/json\n\n{\n  "sender_batch_header": { "sender_batch_id": "tw-{{uniq}}", "email_subject": "Probe" },\n  "items": [{ "recipient_type": "PAYPAL_ID", "amount": { "value": "1.00", "currency": "USD" }, "receiver": "ABCDEFGHJKLMN", "sender_item_id": "tw-{{uniq}}" }]\n}',
  },
];
